/* This file was generated by r.out.leaflet GRASS GIS module. */

var layerInfos = [
   {title: "inundation_0.0", file: "inundation_0.0.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_0.5", file: "inundation_0.5.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_1.0", file: "inundation_1.0.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_1.5", file: "inundation_1.5.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_2.0", file: "inundation_2.0.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_2.5", file: "inundation_2.5.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_3.0", file: "inundation_3.0.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_3.5", file: "inundation_3.5.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_4.0", file: "inundation_4.0.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_4.5", file: "inundation_4.5.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inundation_5.0", file: "inundation_5.0.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
];
