/* This file was generated by r.out.leaflet GRASS GIS module. */

var layerInfos = [
   {title: "inun_0.0", file: "inun_0.0.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inun_0.1", file: "inun_0.1.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
,   {title: "inun_0.2", file: "inun_0.2.png", bounds: [[35.68792709, -78.60830316], [35.80918895, -78.77462049]], opacity: 1.0}
];
